# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: Run Integration Tests

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'The run ID of the build-test-artifacts workflow'
        type: number
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check_run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          conclusion=$(gh run view ${{ inputs.build_run_id }} --repo $GITHUB_REPOSITORY --json conclusion -q '.conclusion')
          if [[ $conclusion == "success" ]]; then
            echo "Run succeeded"
          else
            echo "Run failed"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
